### ISSUE TITLE
How to enhance contrast for this image

### ISSUE THREAD

**Issue by aspenlin** [AndyHuang1995/Image-Contrast-Enhancement#2]
For images like this one (images with text of low contrast), what parameters should I change for a better result?

![contrast](https://user-images.githubusercontent.com/22419710/61808921-5a55f700-ae0a-11e9-8d61-f0b1bbe03a2d.jpeg)

I tried the default values with dhe.py and ying.py, it did help enhance the contrast a little bit but not much. I'm wondering whether the author knows better about how to tune some parameters in the program to get a better result for images like the one I provided.

Thank you very much for the code and for your help!

**Comment by AndyHuang1995** [comment]
Maybe deblur method is what you actually need ?

**Comment by lrscse** [comment]
Hi @AndyHuang1995  i got this error.. how to fix this

Traceback (most recent call last):
  File "dhe.py", line 109, in <module>
    main()
  File "dhe.py", line 102, in main
    img_name = sys.argv[1]
IndexError: list index out of range
