### ISSUE TITLE
KeyError: "None of [Index(['file_path'], dtype='object')] are in the [columns]

### ISSUE THREAD

**Issue by ankita21prasad** [AndyHuang1995/Image-Contrast-Enhancement#8]
I tried to run the file Ying.py and it's giving me the following error while trying to call the function. I couldn't understand what is causing this error. I want to do some image enhancement so that my model can better understand them while training. This is how I called the function to perform image enhancement on multiple images. log is a simple print function defined by me to print data with the date-time appended to a file.

```

def imgOptim():
    print('started')
    root_dir = 'Contrast_Corrected'
    log("####################### image Optimization started ######################")
    #data_csv = pd.read_csv("DataSet_Final.csv")

    #create directory structure for saving cropped images
    os.mkdir(root_dir)
    classes_dir = ['Andy_Serkis', 'Angelina_Jolie', 'David_Schwimmer', 'Jennifer_Aniston', 'Lou_Ferrigno']

    ################Processing Started for Cropping face images######################
    log("Image Correction Script started at :: ")
    processed_dir = 'Cropped Images'
    for cls in classes_dir:
        src = processed_dir + "\\" + cls  # Folder to copy images from

        allFileNames = os.listdir(src)
        os.makedirs(root_dir + '\\' + cls)
        print(allFileNames)

        # Copy-pasting images
        for name in allFileNames:
            img_path = src + '\\' + name
            print(img_path)
            image = imageio.imread(img_path)
            print(image)
            result = Ying_2017_CAIP(image)
            contrast = result.astype('float32')
            #optim.save(os.path.join(root_dir+'\\'+cls, name))
            cv2.imwrite(os.path.join(root_dir+'\\'+cls, name), cv2.cvtColor(contrast, cv2.COLOR_RGB2BGR))

    log("Script Ended at :: ")
```
   

Error I faced: 

Traceback (most recent call last):
  File "C:/DIP_Ankita/image_corrector.py", line 12, in <module>
    data = data[['file_path']]
  File "C:\Users\srchirag27\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\frame.py", line 3001, in __getitem__
    indexer = self.loc._convert_to_indexer(key, axis=1, raise_missing=True)
  File "C:\Users\srchirag27\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\indexing.py", line 1285, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "C:\Users\srchirag27\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\indexing.py", line 1092, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "C:\Users\srchirag27\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\indexing.py", line 1177, in _validate_read_indexer
    key=key, axis=self.obj._get_axis_name(axis)
KeyError: "None of [Index(['file_path'], dtype='object')] are in the [columns]"

**Comment by ankita21prasad** [comment]
It was some issue with saving the file. The code gave amazing results.
